name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v5

     - name: run bash command
       run: ls -al

     - name: Copy files via SSH
       uses: appleboy/scp-action@v1
       with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./
          target: ./

     -  name: Copy files to /var/www/html
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            ls -al
            sudo cp -r * /usr/share/nginx/html
            sudo systemctl restart nginx
    
